Legacysurvey example nb and related plotting cosmetics
oda-hub/oda_api pull request #130
Opened 2022-02-22 12:25 UTC by dsavchenko

2022-03-15 18:53 UTC, burnout87 approved these changes

2022-03-18 08:21 UTC, volodymyrss approved these changes

2022-03-18 08:23 UTC, volodymyrss requested changes
The images do not show it seems https://oda-api--130.org.readthedocs.build/en/130/user_guide/LegacySurvey.html

Compare to https://oda-api--130.org.readthedocs.build/en/130/user_guide/Show_and_Save_Products.html

2022-03-18 10:11 UTC, dsavchenko commented
@volodymyrss does it rebuild automatically? 
Could you check now?

2022-03-18 10:20 UTC, volodymyrss approved these changes

2022-03-18 14:17 UTC, burnout87 approved these changes

2022-03-21 16:05 UTC, merged