allow digits and some characters in url path
oda-hub/oda_api pull request #237
Opened 2024-01-29 17:07 UTC by dsavchenko

These are definitely allowed by standards. Hope we won't encounter a need to use a path with url-encoded / some more allowed symbols

2024-01-29 21:11 UTC, burnout87 commented
> These are definitely allowed by standards. Hope we won't encounter a need to use a path with url-encoded / some more allowed symbols

Would it be possible to provide an example/test ?

2024-01-29 21:39 UTC, volodymyrss requested changes
This function is for validating dispatcher URLs specifically, which are narrower for a variety of reasons.
And it's helpful to notice likely incorrect URLs.

If you have new cases, please do modify, but also add some tests in there:

https://github.com/oda-hub/oda_api/blob/8316675687bb75627ac8a3b352312bc387091d3b/tests/test_basic.py#L249

2024-01-29 22:19 UTC, dsavchenko commented
I had created a somewhat obfuscated url to directly access the staging dispatcher.
It contains digits in the path part. I can change it, of course, but I see no reason for path to not contain digits. Tilde and dot are probably overshoot, I agree.

2024-01-29 22:22 UTC, volodymyrss commented
> I had created a somewhat obfuscated url to directly access the staging dispatcher. It contains digits in the path part. I can change it, of course, but I see no reason for path to not contain digits. Tilde and dot are probably overshoot, I agree.

Sure, add numbers.

2024-01-29 22:41 UTC, volodymyrss approved these changes

2024-01-29 22:53 UTC, volodymyrss commented
> The failed live-test looks completely unrelated. Is it some transient issue with isgri?

Probably. Strange. By the way, something very strange is going on with testing all UNIGE sites since 3 days, even very basic ones, according to https://status.odahub.io/ they are going up and down all the time, i.e. randomly refuse connections. But I did not actually see failing response personally. Might be some new network filter according to some origins.

> Seems I'm not authorized to merge here, so please do if you agree

Ok

2024-01-29 22:53 UTC, merged

2024-01-29 22:54 UTC, volodymyrss commented
> > These are definitely allowed by standards. Hope we won't encounter a need to use a path with url-encoded / some more allowed symbols
> 
> Would it be possible to provide an example/test ?

I think this comment was addressed, but please protest if not, @burnout87 !

2024-01-30 09:51 UTC, burnout87 commented
> > > These are definitely allowed by standards. Hope we won't encounter a need to use a path with url-encoded / some more allowed symbols
> > 
> > 
> > Would it be possible to provide an example/test ?
> 
> I think this comment was addressed, but please protest if not, @burnout87 !

My bad, I forgot to request the change, in any case I guess we'll have examples in the future.

2024-01-30 21:40 UTC, volodymyrss commented
> > > > These are definitely allowed by standards. Hope we won't encounter a need to use a path with url-encoded / some more allowed symbols
> > > 
> > > 
> > > Would it be possible to provide an example/test ?
> > 
> > 
> > I think this comment was addressed, but please protest if not, @burnout87 !
> 
> My bad, I forgot to request the change, in any case I guess we'll have examples in the future.

Examples are included in the tests, or did you mean something else?

2024-01-31 08:48 UTC, burnout87 commented
> 
> Examples are included in the tests, or did you mean something else?

it's ok, I didnt see the tests after they were added