Encode structured param
oda-hub/oda_api pull request #238
Opened 2024-01-30 09:49 UTC by dsavchenko

2024-02-06 16:30 UTC, burnout87 requested changes
I guess this will also need some test, once https://github.com/oda-hub/dispatcher-app/pull/649 is merged...

2024-02-06 18:46 UTC, dsavchenko commented
It's tested by `test_structured_param` in https://github.com/oda-hub/dispatcher-plugin-nb2workflow/pull/82

But I may think of adding the standalone test

2024-02-07 08:30 UTC, volodymyrss approved these changes

2024-02-07 08:49 UTC, burnout87 approved these changes

2024-02-07 14:28 UTC, dsavchenko commented
Could you merge?

2024-02-07 14:29 UTC, merged