158 notebooks should have access to requesters oda token
oda-hub/oda_api pull request #248
Opened 2024-05-07 14:37 UTC by okolo

2024-05-07 18:08 UTC, dsavchenko requested changes
The name of the PR is misleading for the moment. It only changes the way how the callback is passed and doesn't deal with the token. To actually use the context file to get a token, the `token.py` needs to be updated.

2024-05-08 07:15 UTC, okolo commented on oda_api/api.py
> -        callback_file = ".oda_api_callback"  # perhaps it would be better to define this constant in a common lib
done

2024-05-12 14:47 UTC, okolo commented
Currently test fails due to error while running Show_and_Save_Products.ipynb during request to 'https://www.astro.unige.ch/mmoda/dispatch-data' to search for thermonuclear bursts in the JEM-X light curve with error message "something went quite wrong, and we think it's not likely to recover on its own: [ RequestNotUnderstood: RequestNotUnderstood():[ InstrumentQueryBackEnd : jemx ] constructor failed: Found two non aliased identical job_id ]". The behavior is similar in master branch. I am attaching  @volodymyrss do you have any suggestions?

2024-05-14 09:35 UTC, volodymyrss commented
> Currently test fails due to error while running Show_and_Save_Products.ipynb during request to 'https://www.astro.unige.ch/mmoda/dispatch-data' to search for thermonuclear bursts in the JEM-X light curve with error message "something went quite wrong, and we think it's not likely to recover on its own: [ RequestNotUnderstood: RequestNotUnderstood():[ InstrumentQueryBackEnd : jemx ] constructor failed: Found two non aliased identical job_id ]". The behavior is similar in master branch. @volodymyrss do you have any suggestions?

What if you just download and run the notebook, does it fail in the same way?

2024-05-14 10:38 UTC, okolo commented
> > Currently test fails due to error while running Show_and_Save_Products.ipynb during request to 'https://www.astro.unige.ch/mmoda/dispatch-data' to search for thermonuclear bursts in the JEM-X light curve with error message "something went quite wrong, and we think it's not likely to recover on its own: [ RequestNotUnderstood: RequestNotUnderstood():[ InstrumentQueryBackEnd : jemx ] constructor failed: Found two non aliased identical job_id ]". The behavior is similar in master branch. @volodymyrss do you have any suggestions?
> 
> What if you just download and run the notebook, does it fail in the same way?

I've tried to run the notebook in jupyter. The error persists. Here is the notebook output 
[Show_and_Save_Products.html.zip](https://github.com/oda-hub/oda_api/files/15307134/Show_and_Save_Products.html.zip)

2024-05-14 21:00 UTC, volodymyrss commented
> > > Currently test fails due to error while running Show_and_Save_Products.ipynb during request to 'https://www.astro.unige.ch/mmoda/dispatch-data' to search for thermonuclear bursts in the JEM-X light curve with error message "something went quite wrong, and we think it's not likely to recover on its own: [ RequestNotUnderstood: RequestNotUnderstood():[ InstrumentQueryBackEnd : jemx ] constructor failed: Found two non aliased identical job_id ]". The behavior is similar in master branch. @volodymyrss do you have any suggestions?
> > 
> > 
> > What if you just download and run the notebook, does it fail in the same way?
> 
> I've tried to run the notebook in jupyter. The error persists. Here is the notebook output [Show_and_Save_Products.html.zip](https://github.com/oda-hub/oda_api/files/15307134/Show_and_Save_Products.html.zip)

Looks like there was some strange behavior with this product on the live instance, must be related to a recent update.
Anyway now it's passing.

2024-05-15 09:54 UTC, dsavchenko approved these changes

2024-05-15 09:56 UTC, volodymyrss approved these changes

2024-05-15 11:46 UTC, merged