WIP: Adapt example notebooks to release
oda-hub/oda_api pull request #67
Opened 2021-08-24 11:54 UTC by ferrigno

Need to verify my modification, as the archive is not mounted.

2021-09-01 15:10 UTC, ferrigno commented
I have reviewed the notebooks and they seem to all work.
I have also changed a default value to display images.

2021-09-06 07:06 UTC, ferrigno commented
@volodymyrss I am waiting for your review

2021-09-06 08:13 UTC, volodymyrss requested changes
some comments to Async apply also to Auth.
Thanks!

2021-09-06 08:13 UTC, volodymyrss commented on doc/source/user_guide/AsynchronousAPI.ipynb
> +    "        T2_utc='%4d-12-31T23:59:59.0'%year # there are 30 days in June!\n",
there are, however, 31 days in December

2021-09-06 08:13 UTC, volodymyrss commented on doc/source/user_guide/AsynchronousAPI.ipynb
> +      "Is complete  True\n"
it's pretty clear that this loop over multiple request args is very reusable and could be all in a function like `get_product_set()`. But users might want to implement some custom async requests too, so it's not bad to have this custom example. I would even keep this example and then add at the end "by the way, we made a convenience function for this". For the future.

2021-09-06 08:13 UTC, volodymyrss commented on doc/source/user_guide/Authentication.ipynb
> +    "If you do not have an account create one, by clicking always on Sign-in nad then create new account.\n",
`nad` => `and`

2021-09-07 15:35 UTC, ferrigno commented on doc/source/user_guide/AsynchronousAPI.ipynb
>      "token = getpass.getpass('Insert the token')"
What is 'exp' ? in decode token?

discover_token() returns None , what is it about?

oda_api.token.decode_oda_token(token)

{'sub': 'Carlo.Ferrigno@unige.ch',
 'email': 'Carlo.Ferrigno@unige.ch',
 'name': 'cferrigno',
 'roles': 'authenticated user, administrator, content manager, general, integral-private-qla, magic, unige-hpc-full, public-pool-hpc, antares, sdss',
 'exp': 1631110932}

2021-09-07 15:40 UTC, merged

2021-09-07 15:44 UTC, burnout87 commented on doc/source/user_guide/AsynchronousAPI.ipynb
>      "token = getpass.getpass('Insert the token')"
It's the expiration time in seconds.

2021-09-07 16:02 UTC, volodymyrss commented on doc/source/user_guide/AsynchronousAPI.ipynb
>      "token = getpass.getpass('Insert the token')"
> What is 'exp' ? in decode token?

that's right, time when the token expires, in unix seconds. Can be used as so:

https://github.com/oda-hub/oda_api/blob/5c762edd597d7bbc8573c94d03df906ba1b10891/oda_api/cli.py#L86-L91
(I guess let's not document cli yet)

> discover_token() returns None , what is it about?

it means there is no token in the system.

you can see the methods of discovery in here:

https://github.com/oda-hub/oda_api/blob/5c762edd597d7bbc8573c94d03df906ba1b10891/oda_api/token.py#L75-L83

it should be relatively clear what are the 3 methods:

* ODA_TOKEN env variable
* ./.oda-token file
* ~/.oda-token file


> 
> oda_api.token.decode_oda_token(token)
> 
> {'sub': '[Carlo.Ferrigno@unige.ch](mailto:Carlo.Ferrigno@unige.ch)',
> 'email': '[Carlo.Ferrigno@unige.ch](mailto:Carlo.Ferrigno@unige.ch)',
> 'name': 'cferrigno',
> 'roles': 'authenticated user, administrator, content manager, general, integral-private-qla, magic, unige-hpc-full, public-pool-hpc, antares, sdss',
> 'exp': 1631110932}